name: Run ERT tests

on:
  workflow_call:
  pull_request:
    branches:
      - "trunk"
    paths:
      - "**"
      - "!**.md"
      - "!**.org"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - snapshot
          - release-snapshot

    steps:
      - uses: actions/checkout@v3.5.3

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: conao3/setup-cask@master
        with:
          version: snapshot
      
      - name: Install Nix grammar
        run: |
          emacs -batch -l test/scripts/install-nix-grammar.el

      - name: Run tests
        run: make test
      
      - name: Cleanup
        run: make clean